### PR TITLE
Mappings

### PR DESCRIPTION
**Pull request by ghost**
- Entities
- Blocks

### CODE REVIEW

**Comment by ellisong** [comment]
@MrIbby  Some of these entities make a lot of sense to have. Have you tested it 5 months later with the current version?

**Comment by ghost** [comment]
@ellisong Nope! @FyberOptic hasn't shown any interest, so I don't feel like putting in more effort.

**Comment by FyberOptic** [comment]
I coulda sworn that I replied to this thread months ago but obviously I didn't, and then honestly just forgot about it.  Sorry if it seemed like I just ignored you or your work.

The reason I never merged initially was because you added quite a few things, which is good in respect for mappings, but bad in respect of time to dig each class up and review how you detect it.  I'm always worried about mappings being misdetected in later versions, because that's happened in the past and led to a lot of confusing issues.  And I didn't want to just pick out individual things from your commit and add them manually because then you don't get credit, so it was all or nothing, basically.

You might have noticed that I went from cranking out new mappings in 2015 to just maintaining what was here, because I got busier again a few months ago and unfortunately had to give this project a lower priority.  

Anyhoo, excuses excuses, etc.  I don't like making promises I can't keep, but I can at least promise to start looking over it again the next time I have DynamicMappings open, because these would be good mappings to have.

**Comment by ghost** [comment]
> [...] because then you don't get credit [...]

I don't care much for credit, so do as you please. If necessary, I'll license my contributions under MIT (or whatever public domain license).

**Comment by ghost** [comment]
🎉

**Comment by FyberOptic** [comment]
It's a ~~Christmas~~, ~~Spring~~, Summer miracle!

**Pull request merged**
