### PR TITLE
Reworked some old mappings

### PR DESCRIPTION
**Pull request by canitzp**

### CODE REVIEW

**Comment by FyberOptic** [comment]
I don't really consider these mappings reworkings to be reliable, if I'm to be honest.

I intentionally make them convoluted so that they have a higher possibility of failure if Mojang changes things.  Matching by signature alone is not very preferable, especially when trying to discover classes.  Whenever there's the possibility to search a constant pool for a string, I try to take it.  

I also don't consider matching methods by order of appearance to be very reliable either.  I may have used this on an occasion or two, I can't recall, but if there's ever any other possible way to discover these mappings from another location more accurately, then I always prefer that.  When the owner class doesn't offer a lot of clues, sometimes I have to use the decompiled jar in Eclipse to backtrack to a more reliable place.

Mojang is very unreliable and very prone to changing signatures on a whim.  So DynamicMappings is already one big house of cards with a high probability of failure on updates.  I always try to make sure that the failures come from inability to detect a class (or method) rather than a misdetection, because a misdetection is far harder to debug.

**Comment by canitzp** [comment]
Okay, I understand and support your point and sometimes I don't write very dynamic methods. A bug problem is if mojang change one signature a lot of mappings breaks, but this is the problem if anyone adds new mappings. Now these are max 20 mappings, but these does increase. DynamicMappings isn't dynamic enough, but it is a good recompiling and deobfuscating tool and to add mappings or to rework older ones, if new ways are included is important for the future of it. I think it is easier if anyone would add new helpet methods per example 'getMethodsContainsStringsFromClass'. I try to do such helper, but nearly everything I learn about class transforming or deobfuscating, came from DynamicMappings. I only can learn more if other add new things I can learn from, so maybe I'm not the best guy to write helper methods.

**Comment by FyberOptic** [comment]
If Mojang changes a signature then chances are things are going to break somewhere anyway, if not in the API layer then in the mods themselves (several of my mods are currently broken).  DynamicMappings has to be designed in a hierarchical fashion, getting mappings based on other mappings, so we'll always have this issue.  I don't really mind fixing the mappings though since it lets me see what exactly is different, and why they might have done it.  Many times very little is required to fix them.

And yeah, we can always use useful helper methods, since they make the code a bit cleaner to read.  The one downside is that very many of them can get a bit tricky to keep track of, especially for people new to the project, but I guess there's not much one can do about that.  A method to extract strings, and then another to find a method with a specific string, would also be useful.  I can add that.

**Comment by canitzp** [comment]
I update my fork and to be more save I try to use strings to find the classes and methods

**Comment by canitzp** [comment]
Updated it. more I cannot check without writing complicated methods. If you no want the changes than please close the pr

**Comment by FyberOptic** [comment]
I feel a bit bad to let someone's efforts go to waste but I think I'm just more comfortable if we leave existing mappings alone for the most part.   I just don't trust Mojang to not screw it all up.

**Comment by canitzp** [comment]
It's okay. What are you thinking of an event system for meddle. my waila mod for the snapshots use really bad class transforming, cause I'm not so good with this

**Comment by FyberOptic** [comment]
Open an issue on MeddleAPI for that with what you're trying to do and we can look into it.

**Pull request closed without merging**
